# Generated by Django 2.2.1 on 2021-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockNum', models.CharField(db_index=True, max_length=15, verbose_name='股票代码')),
                ('transactionDay', models.CharField(max_length=15, verbose_name='交易日')),
                ('transactionTime', models.IntegerField(verbose_name='交易时间')),
                ('pricePreviousday', models.FloatField(verbose_name='前日收盘价')),
                ('priceOpening', models.FloatField(verbose_name='开盘价')),
                ('priceHigh', models.FloatField(verbose_name='最高价')),
                ('priceLow', models.FloatField(verbose_name='最低价')),
                ('priceNow', models.FloatField(verbose_name='当前价')),
                ('priceSell', models.FloatField(null=True, verbose_name='申卖价')),
                ('sellAmount', models.FloatField(null=True, verbose_name='申卖量')),
                ('priceBuy', models.FloatField(null=True, verbose_name='申买价')),
                ('buyAmount', models.FloatField(null=True, verbose_name='申买量')),
                ('transactionNum', models.FloatField(null=True, verbose_name='成交笔数')),
                ('transactionNumtotal', models.FloatField(verbose_name='成交总量')),
                ('transactionPricetotal', models.FloatField(verbose_name='成交总金额')),
            ],
            options={
                'verbose_name': '当日数据',
                'verbose_name_plural': '当日数据',
                'db_table': 'daydata',
            },
        ),
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockNum', models.CharField(db_index=True, max_length=15, verbose_name='股票代码')),
                ('transactionDay', models.CharField(max_length=15, verbose_name='交易日')),
                ('transactionTime', models.IntegerField(verbose_name='交易时间')),
                ('pricePreviousday', models.FloatField(verbose_name='前日收盘价')),
                ('priceOpening', models.FloatField(verbose_name='开盘价')),
                ('priceHigh', models.FloatField(verbose_name='最高价')),
                ('priceLow', models.FloatField(verbose_name='最低价')),
                ('priceNow', models.FloatField(verbose_name='当前价')),
                ('priceSell', models.FloatField(verbose_name='申卖价')),
                ('sellAmount', models.FloatField(verbose_name='申卖量')),
                ('priceBuy', models.FloatField(verbose_name='申买价')),
                ('buyAmount', models.FloatField(verbose_name='申买量')),
                ('transactionNum', models.FloatField(verbose_name='成交笔数')),
                ('transactionNumtotal', models.FloatField(verbose_name='成交总量')),
                ('transactionPricetotal', models.FloatField(verbose_name='成交总金额')),
            ],
            options={
                'verbose_name': '历史K线',
                'verbose_name_plural': '历史K线',
                'db_table': 'kline',
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockNum', models.CharField(max_length=50, verbose_name='股票代码')),
                ('stockName', models.CharField(max_length=50, verbose_name='股票名称')),
            ],
            options={
                'verbose_name': '股票名称',
                'verbose_name_plural': '股票名称',
                'db_table': 'stockdata',
            },
        ),
    ]
